import * as React from "react";
export const Home = () => {
    return (React.createElement("div", { className: "fahome" },
        React.createElement("header", { className: "masthead" },
            React.createElement("div", { className: "container" },
                React.createElement("div", { className: "masthead-subheading" }, "Limited Liability Company"),
                React.createElement("div", { className: "masthead-heading text-uppercase" }, "ForAy Inspections"),
                React.createElement("a", { className: "btn btn-primary btn-xl text-uppercase js-scroll-trigger", href: "#contact" }, "Contact"))),
        React.createElement("section", { style: { color: "#fff" }, className: "page-section", id: "services" },
            React.createElement("div", { className: "container" },
                React.createElement("div", { className: "text-center" },
                    React.createElement("h2", { className: "section-heading text-uppercase" }, "Services")),
                React.createElement("div", { className: "row text-center" },
                    React.createElement("div", { className: "col-md-4 welding" },
                        React.createElement("h4", { className: "my-3" }, "Certified Welding Inspector"),
                        React.createElement("p", { className: "text-muted" }, "License#: 1911311")),
                    React.createElement("div", { className: "vertical-row" }),
                    React.createElement("div", { className: "col-md-4 cali" },
                        React.createElement("h4", { className: "my-3 " }, "Southern Califonia Regional"),
                        React.createElement("p", { className: "text-muted" }, "Greater Los Angeles Area")),
                    React.createElement("div", { className: "vertical-row" }),
                    React.createElement("div", { className: "col-md-4 vetpwnd" },
                        React.createElement("h4", { className: "my-3" }, "Vet Owned"),
                        React.createElement("p", { className: "text-muted" }, "The owner has contributed his own life for and on the very soil you require inspecting. Allow to let him give your peice of mind reign. "))))),
        React.createElement("section", { className: "page-section bg-light", id: "team" },
            React.createElement("div", { className: "container" },
                React.createElement("div", { className: "text-center" },
                    React.createElement("h2", { className: "section-heading text-uppercase" }, "AyMazing Team")),
                React.createElement("div", { className: "row" },
                    React.createElement("div", { className: "col-md-12" },
                        React.createElement("div", { className: "team-member" },
                            React.createElement("img", { className: "mx-auto rounded-circle", src: "assets/img/124754cdb18130f1bbdcd40d2e18208a--mr-bean-so-funny.png", alt: "" }),
                            React.createElement("h4", null, "Anthony \"AyOne\" Ramirez"),
                            React.createElement("p", { className: "text-muted" }, "Owner"),
                            React.createElement("a", { className: "btn btn-dark btn-social mx-2", href: "#!" },
                                React.createElement("i", { className: "fa fa-twitter" })),
                            React.createElement("a", { className: "btn btn-dark btn-social mx-2", href: "#!" },
                                React.createElement("i", { className: "fa fa-facebook-f" })),
                            React.createElement("a", { className: "btn btn-dark btn-social mx-2", href: "#!" },
                                React.createElement("i", { className: "fa fa-linkedin" })),
                            React.createElement("a", { className: "btn btn-dark btn-social mx-2", href: "#!" },
                                React.createElement("i", { className: "fa fa-instagram" }))))),
                React.createElement("div", { className: "row" },
                    React.createElement("div", { className: "col-lg-8 mx-auto text-center" },
                        React.createElement("p", { className: "large text-muted" }, "Anthony has come a long way from playing computer games and working a Jack in the Box Drive Thru. Through out the years hes exposed himself to the most lethal enviornments. Now that he's been back home he can really prove to himself on the soil he fought for. Anthony is heavily trained for combat but his customer service has always exceeded his customers expectations with his aggressive attitude to find solution."))))),
        React.createElement("section", { className: "page-section", id: "contact" },
            React.createElement("div", { className: "container" },
                React.createElement("div", { className: "text-center" },
                    React.createElement("h2", { className: "section-heading text-uppercase" }, "Contact Us"),
                    React.createElement("h3", { className: "section-subheading text-muted" }, "Lorem ipsum dolor sit amet consectetur.")),
                React.createElement("form", { id: "contactForm", name: "sentMessage" },
                    React.createElement("div", { className: "row align-items-stretch mb-5" },
                        React.createElement("div", { className: "col-md-6" },
                            React.createElement("div", { className: "form-group" },
                                React.createElement("input", { className: "form-control", id: "name", type: "text", placeholder: "Your Name *", "data-validation-required-message": "Please enter your name." }),
                                React.createElement("p", { className: "help-block text-danger" })),
                            React.createElement("div", { className: "form-group" },
                                React.createElement("input", { className: "form-control", id: "email", type: "email", placeholder: "Your Email *", "data-validation-required-message": "Please enter your email address." }),
                                React.createElement("p", { className: "help-block text-danger" })),
                            React.createElement("div", { className: "form-group mb-md-0" },
                                React.createElement("input", { className: "form-control", id: "phone", type: "tel", placeholder: "Your Phone *", "data-validation-required-message": "Please enter your phone number." }),
                                React.createElement("p", { className: "help-block text-danger" }))),
                        React.createElement("div", { className: "col-md-4" },
                            React.createElement("div", { className: "form-group form-group-textarea mb-md-0" },
                                React.createElement("textarea", { className: "form-control", id: "message", placeholder: "Your Message *", "data-validation-required-message": "Please enter a message." }),
                                React.createElement("p", { className: "help-block text-danger" })))),
                    React.createElement("div", { className: "text-center" },
                        React.createElement("div", { id: "success" }),
                        React.createElement("button", { className: "btn btn-primary btn-xl text-uppercase", id: "sendMessageButton", type: "submit" }, "Send Message"))))),
        React.createElement("footer", { className: "footer row" },
            React.createElement("div", { className: "container" },
                React.createElement("div", { className: "ep-footerbar" },
                    React.createElement("span", { className: "ep-copyright", style: { color: "white" } }, "Elicit \u00A92020  |  All Rights Reserved"),
                    React.createElement("nav", { className: "footer-nav pull-right" },
                        React.createElement("ul", null,
                            React.createElement("li", null,
                                React.createElement("a", { className: "btn btn-dark btn-social mx-2", href: "#!" },
                                    React.createElement("i", { className: "fa fa-twitter" }))),
                            React.createElement("li", null,
                                React.createElement("a", { className: "btn btn-dark btn-social mx-2", href: "#!" },
                                    React.createElement("i", { className: "fa fa-facebook" }))),
                            React.createElement("li", null,
                                React.createElement("a", { className: "btn btn-dark btn-social mx-2", href: "#!" },
                                    React.createElement("i", { className: "fa fa-linkedin" }))),
                            React.createElement("li", null,
                                React.createElement("a", { className: "btn btn-dark btn-social mx-2", href: "#!" },
                                    React.createElement("i", { className: "fa fa-instagram" }))))))))));
};
//# sourceMappingURL=Home.js.map