import * as React from "react";
export const Home = () => {
    return (React.createElement("div", { className: "fahome" },
        React.createElement("header", { className: "masthead" },
            React.createElement("div", { className: "container" },
                React.createElement("div", { className: "masthead-subheading" }, "Limited Liability Company"),
                React.createElement("div", { className: "masthead-heading text-uppercase" }, "Foray Inspection"),
                React.createElement("a", { className: "btn btn-primary btn-xl text-uppercase js-scroll-trigger", href: "#contact" }, "Contact"))),
        React.createElement("section", { style: { color: "#fff" }, className: "page-section", id: "services" },
            React.createElement("div", { className: "container" },
                React.createElement("div", { className: "text-center" },
                    React.createElement("h2", { className: "section-heading text-uppercase" }, "Services")),
                React.createElement("div", { className: "row text-center" },
                    React.createElement("div", { className: "col-md-4 welding" },
                        React.createElement("h4", { className: "my-3" }, "Certified Welding Inspector"),
                        React.createElement("p", { className: "text-muted" }, "License#: 1911311")),
                    React.createElement("div", { className: "col-md-4 cali" },
                        React.createElement("h4", { className: "my-3 " }, "Southern Califonia Regional"),
                        React.createElement("p", { className: "text-muted" }, "Greater Los Angeles Area")),
                    React.createElement("div", { className: "col-md-4 vetpwnd" },
                        React.createElement("h4", { className: "my-3" }, "Vet Owned"),
                        React.createElement("p", { className: "text-muted" }, "The owner has contributed his own life for and on the very soil you require inspecting. Allow to let him give your peice of mind reign. "))))),
        React.createElement("section", { className: "page-section bg-light", id: "team" },
            React.createElement("div", { className: "container" },
                React.createElement("div", { className: "text-center" },
                    React.createElement("h2", { className: "section-heading text-uppercase" }, "AyMazing Team")),
                React.createElement("div", { className: "row" },
                    React.createElement("div", { className: "col-md-12" },
                        React.createElement("div", { className: "team-member" },
                            React.createElement("img", { className: "mx-auto rounded-circle", src: "assets/img/mrbeansofunny.png", alt: "" }),
                            React.createElement("h4", null, "Anthony \"AyOne\" Ramirez"),
                            React.createElement("p", { className: "text-muted" }, "Owner"),
                            React.createElement("a", { className: "btn btn-dark btn-social mx-2", href: "#!" },
                                React.createElement("i", { className: "fa fa-twitter" })),
                            React.createElement("a", { className: "btn btn-dark btn-social mx-2", href: "#!" },
                                React.createElement("i", { className: "fa fa-facebook-f" })),
                            React.createElement("a", { className: "btn btn-dark btn-social mx-2", href: "#!" },
                                React.createElement("i", { className: "fa fa-linkedin" })),
                            React.createElement("a", { className: "btn btn-dark btn-social mx-2", href: "#!" },
                                React.createElement("i", { className: "fa fa-instagram" }))))),
                React.createElement("div", { className: "row" },
                    React.createElement("div", { className: "col-lg-8 mx-auto text-center" },
                        React.createElement("p", { className: "large text-muted" }, "Anthony has come a long way from playing computer games and working a Jack in the Box Drive Thru. Through out the years hes exposed himself to the most lethal enviornments. Now that he's been back home he can really prove to himself on the soil he fought for. Anthony is heavily trained for combat but his customer service has always exceeded his customers expectations with his aggressive attitude to find solution."))))),
        React.createElement("section", { className: "page-section", id: "contact" },
            React.createElement("div", { className: "container" },
                React.createElement("div", { className: "text-center" },
                    React.createElement("h2", { className: "section-heading text-uppercase" }, "Contact Us"),
                    React.createElement("h3", { className: "section-subheading text-muted" }, "Feel free to give us a call or email."),
                    React.createElement("h4", { style: { color: "white" } }, "Anthony Ramirez"),
                    React.createElement("a", { href: "tel:5624566001" }, "Phone: (562) 456-6001"),
                    React.createElement("br", null),
                    React.createElement("a", { href: "mailto:dispatch@forayinspection.com?subject=Contact" }, "Dispatch@ForayInspection.com")))),
        React.createElement("footer", { className: "footer row" },
            React.createElement("div", { className: "container" },
                React.createElement("div", { className: "ep-footerbar" },
                    React.createElement("span", { className: "ep-copyright", style: { color: "white" } }, "Elicit \u00A92020  |  All Rights Reserved"),
                    React.createElement("nav", { className: "footer-nav pull-right" },
                        React.createElement("ul", null,
                            React.createElement("li", null,
                                React.createElement("a", { className: "btn btn-dark btn-social mx-2", href: "#!" },
                                    React.createElement("i", { className: "fa fa-twitter" }))),
                            React.createElement("li", null,
                                React.createElement("a", { className: "btn btn-dark btn-social mx-2", href: "#!" },
                                    React.createElement("i", { className: "fa fa-facebook" }))),
                            React.createElement("li", null,
                                React.createElement("a", { className: "btn btn-dark btn-social mx-2", href: "#!" },
                                    React.createElement("i", { className: "fa fa-linkedin" }))),
                            React.createElement("li", null,
                                React.createElement("a", { className: "btn btn-dark btn-social mx-2", href: "#!" },
                                    React.createElement("i", { className: "fa fa-instagram" }))))))))));
};
//# sourceMappingURL=Home.js.map